DROP SEQUENCE SEQ_MEMBER_NUM;
DROP TABLE MEMBER CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_MEMO_NUM;
DROP TABLE MEMO CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE SEQ_MUSIC_NUM;
DROP TABLE MUSIC CASCADE CONSTRAINTS PURGE;

CREATE SEQUENCE SEQ_MEMBER_NUM START WITH 1 MAXVALUE 99999999999999 MINVALUE 1 NOCYCLE CACHE 20  NOORDER;
CREATE SEQUENCE SEQ_MEMO_NUM START WITH 1 MAXVALUE 99999999999999 MINVALUE 1 NOCYCLE CACHE 20  NOORDER;
CREATE SEQUENCE SEQ_MUSIC_NUM START WITH 1 MAXVALUE 99999999999999 MINVALUE 1 NOCYCLE CACHE 20  NOORDER;

CREATE TABLE MEMBER
(
	MEMBER_NUM                NUMBER(3)  NOT NULL ,
	EMAIL                 VARCHAR2(500)  NOT NULL ,
	PW                    VARCHAR2(500)  NOT NULL ,
	NAME                  VARCHAR2(500)  NOT NULL ,
	PHONE                 VARCHAR2(500)  NOT NULL ,
	TENDENCY              VARCHAR2(500)  NOT NULL  
);

CREATE UNIQUE INDEX XPK_MEMBER ON MEMBER
(MEMBER_NUM  ASC);
	
CREATE TABLE MEMO
(
	MEMO_NUM                  NUMBER(3)  NOT NULL ,
	MEMBER_NUM                NUMBER(3)  NOT NULL ,
	TITLE                 	  VARCHAR2(500)  NOT NULL ,
	CONTENT                   VARCHAR2(500)  NULL ,
	HASHTAG1                  VARCHAR2(500)  NULL ,
	HASHTAG2                  VARCHAR2(500)  NULL ,
	HASHTAG3                  VARCHAR2(500)  NULL ,
	BACK					  VARCHAR2(500)  NULL ,
	WRITEDAY                  DATE  NOT NULL ,
	MUSIC_NUM                 NUMBER(3)  NOT NULL
);

CREATE TABLE MUSIC
(
	MUSIC_NUM                 NUMBER(3)  NOT NULL ,
	TITLE               	  VARCHAR2(500)  NOT NULL ,
	SINGER                 	  VARCHAR2(500)  NOT NULL ,
	EMOTION					  VARCHAR2(500)  NOT NULL ,
	EMOTION2				  VARCHAR2(500)  NULL ,
	URL	                      VARCHAR2(500)  NULL
);


ALTER TABLE MEMBER
	ADD  PRIMARY KEY (MEMBER_NUM);
	
ALTER TABLE MEMO
	ADD  PRIMARY KEY (MEMO_NUM);	
	
ALTER TABLE MUSIC
	ADD  PRIMARY KEY (MUSIC_NUM);

	
ALTER TABLE MEMO
	ADD ( FOREIGN KEY (MEMBER_NUM) REFERENCES MEMBER(MEMBER_NUM));
	
ALTER TABLE MEMO
	ADD ( FOREIGN KEY (MUSIC_NUM) REFERENCES MUSIC(MUSIC_NUM));	
	
INSERT INTO MEMBER (MEMBER_NUM, EMAIL, PW, NAME, PHONE, TENDENCY) VALUES (SEQ_MEMBER_NUM.NEXTVAL, 'test@naver.com', '123', 'name TEST', '01033331111',	'yes');
COMMIT;
INSERT INTO MUSIC (MUSIC_NUM, TITLE, SINGER, EMOTION, EMOTION2, URL) VALUES (SEQ_MUSIC_NUM.NEXTVAL, 'title TEST', 'singer TEST', '577', '111', '0');
INSERT INTO MUSIC (MUSIC_NUM, TITLE, SINGER, EMOTION, EMOTION2, URL) VALUES (SEQ_MUSIC_NUM.NEXTVAL, 'title TEST2', 'singer TEST2', '111', '577', '0');
COMMIT;
INSERT INTO MEMO (MEMO_NUM, MEMBER_NUM, TITLE, CONTENT, HASHTAG1, HASHTAG2, HASHTAG3, BACK, WRITEDAY, MUSIC_NUM) VALUES (SEQ_MEMO_NUM.NEXTVAL, 1, 'titleTEST', 'contentTEST', 'hash1', 'hash2', 'hash3', 'happy', SYSDATE,	1);
COMMIT;	