DROP SEQUENCE SEQ_MUSIC_NUM;

DROP TABLE MUSIC CASCADE CONSTRAINTS PURGE;

CREATE TABLE MUSIC
(
	MUSIC_NUM                 NUMBER(3)  NOT NULL ,
	TITLE               	  VARCHAR2(500)  NOT NULL ,
	SINGER                 	  VARCHAR2(500)  NOT NULL ,
	EMOTION					  VARCHAR2(500)  NOT NULL ,
	URL	                      VARCHAR2(500)  NULL
);

ALTER TABLE MUSIC
	ADD  PRIMARY KEY (MUSIC_NUM);

CREATE SEQUENCE SEQ_MUSIC_NUM START WITH 1 MAXVALUE 99999999999999 MINVALUE 1 NOCYCLE CACHE 20  NOORDER;

COMMIT;

INSERT INTO MUSIC (MUSIC_NUM, TITLE, SINGER, EMOTION, URL) VALUES (SEQ_MUSIC_NUM.NEXTVAL, '°î¸íTEST', '°¡¼öTEST', 'LOVE', '0');

ALTER TABLE MUSIC
	ADD ( FOREIGN KEY (MUSIC_NUM) REFERENCES MUSIC(MUSIC_NUM));
	
COMMIT;
